### ISSUE TITLE
fresh setup not finding db

### ISSUE THREAD

**Issue by hilyin** [agentejo/cockpit-docker#9]
When I start this up, the error I get is below. I am trying to load just a simple sqlite db install.

```
Oh no! Something went terribly wrong:
SQLSTATE[HY000] [14] unable to open database file
/lib/MongoLite/Database.php
     * @param array  $options
     */
    public function __construct($path = self::DSN_PATH_MEMORY, $options = []) {

        $dns = "sqlite:{$path}";

        $this->path = $path;
        $this->connection = new \PDO($dns, null, null, $options);

        $database = $this;

        $this->connection->sqliteCreateFunction('document_key', function($key, $document){

System message generated by Cockpit debug
```

Below is my docker-compose.yml:

```
version: '3.3'

services:
  cockpit:
    restart: always
    image: agentejo/cockpit
    environment:
      - COCKPIT_SESSION_NAME=cockpit
      - COCKPIT_SALT=not-a-real-salt
    ports:
      - "8080:80"
    volumes:
      - './cockpit/storage:/var/www/html/storage:Z'
```

Thanks.
